<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ES6-12-Promise</title>
</head>
<body>

</body>
<script type="text/javascript">
    // Promise  异步编程的一种解决方案
    // 1.对象的状态不受外界影响  3种状态 Pending(进行中) Fulfilled(已成功)Rejected(已失败) 只有结果可以改变状态
    // 2.一旦状态改变就不会再变  从pending到Fulfilled 和 pending到Rejected不会再变  称为已定型()Resolved

    // 基本用法
    var promise = new Promise(function(resolve, reject){
        // 操作成功
        if(true){
            resolve(value);
        }else{
            reject(error);
        }
    });
    //then方法  两个回调函数作为参数 第一个是成功时调用 第二个失败时调用可选  接受Promise对象传出的值作为参数
    // 可以使用链式写法
    promise.then(function(value){

    },function(error){

    });
    function timeout(ms){
        return new Promise(((resolve, reject) => {
            setTimeout(resolve, ms, "done");
        }));
    }
    timeout(100).then((value) => {
        console.log(value);
    });
    // 异步加载图片
    function loadImageAsync(url){
        return new Promise(function (resolve, reject) {
            var image = new Image();
            image.onload = function(){
                //成功把图片加载到body后面
                resolve(document.getElementsByTagName("body")[0].appendChild(image));
            };
            image.onerror = function(){
                reject(new Error("异步加载图片出错："+ url ));
            };
            image.src = url;
        });
    }
    loadImageAsync("../images/1.jpg");
    // 实现AJAX
    var getJSON = function(url){
        var promise3 = new Promise(function(resolve, reject){
            var client = new XMLHttpRequest();
            client.open("GET",url);
            client.onreadystatechange = handler;
            client.responseText = "json";
            client.setRequestHeader("Accept","application/json");
            client.send();

            function handler(){
                if(this.readyState !== 4){
                    return;
                }
                if(this.status === 200){
                    resolve(this.response);
                }else{
                    reject(new Error(this.statusText));
                }
            };
        });
        return promise3;
    };
    getJSON("../data/json.json").then(function(json){
        console.log("contents:" + json);//成功打印返回json
    },function(error){
        console.log("出错：" + error);
    });
    //嵌套回调函数
    var p1 = new Promise(function(resolve, reject){
        setTimeout(() => reject(new Error("fail")),3000);
    });
    var p2 = new Promise(function(resolve, reject){
        setTimeout(() => resolve(p1),1000);
    });
    p2.then(result => cosnole.log(result)).catch(error => console.log(error));//error fail

    // Promise.prototype.cache()等同于.then(null,rejection)用于指定发生错误的回调函数   Promise有"冒泡"性质，
    // 错误会一直向后传递，都会被catch()捕获，一般不再then()方法中定义rejected（错误的）回调函数（因为promise
    // 在resolve之后再抛出错误并不会被捕获，等于没有抛出，应为promise状态已经改变为成功（fulfilled）不会再改变）
    // 应该使用catch(方法)
    getJSON("../data/json.json").then(function(posts){

    }).catch(function(error){
       //处理getJSON和前一个回调函数运行发生的错误
        console.log("发生错误：",error);
    });
    var promise3 = new Promise(function(resolve, reject){
        throw new Error("test");
    });
    promise3.catch(function(error){
        console.log(error);
    });//Error:  test
    //bad
    promise.then(function(data){
        //success
        },function(error){
        //error
    });
    //good
    promise.then(function(data){
        //success
    }).catch(function(error){
        //error
    });
    // catch()也能抛出错误，由另一个catch()捕获
    var someAsyncThing = function(){
        return new Promise(function(resolve, reject){
           resolve(x + 2);
        });
    };
    someAsyncThing().then(function(){
        return someOtherAsyncThing()
    }).catch(function(error){
        console.log("oh no",error);
        y + 2;
    }).catch(function(error){
        console.log("carry on",error);
    });
    // oh no x is not defined
    // carry on y is not defined  第二个catch方法捕获第一个catch的错误

    // Promise.all()用于将多个Promise实例包装成一个新的Promise实例
    //只要p1,p2全部状态为Fulfilled p的状态才为Fulfiled(成功的)  返回的值成为一个数组
    //只要p1,p2有一个状态不为Fulfilled p的状态就为Rejected(失败的)  返回第一个Rejected的值
    var p11 = Promise.all([p1,p2]);
    // const databasePromise = connectDatabase();   只有都成功才能触发pickTopRecommentations函数
    // const booksPromise = databasePromise.then(findAllBooks);
    // const userPromise = databasePromise.then(getCurrentUser);
    // Promise.all([booksPromise, userPromise]).then(([books, user]) => pickTopRecommentations(books, user));
    const p3 = new Promise((resolve, reject) => {
        resolve("hello");
    }) .then(result => result);
    const p4 = new Promise((resolve, reject) => {
        throw Error("报错了");
    }).then(result => result);
    Promise.all([p3, p4])
        .then(result => console.log(result))
        .catch(e => console.log(e));//报错了

    // Promise.race()将多个Promise实例包装成一个新的Promise实例
    //如果有一个Promise实例率先改变状态，那么p也会跟着改变，率先改变的Promise实例返回值传递给p的回调函数
    var p12 = Promise.race([p1, p2, p3])
    // const p6 = Promise.race([
    //    fecth("/resource-that-may-take-a-while"),
    //    new Promise(function (resolve, reject) {
    //        setTimeout(() => reject(new Error("request timeout")), 5000)
    //    })
    // ]);
    // p6.then(reporter => console.log(response));
    // p6.catch(error => console.log(error));

    // Promise.resolve()将现有对象转为Promise对象
    // 参数是一个Promise实例  返回这个实例
    // 参数是一个thenable对象  指具有then方法的对象  转为Promise对象，立即执行thenable对象的then方法
    let thenable = {
        then:function(resolve, reject){
            resolve(42);
        }
    };
    let p7 = Promise.resolve(thenable);
    p7.then(function(value){
        console.log(value);
    });//42
    // 参数不是thenable对象或者不是对象 返回一个新的Promise对象 状态为Resolved
    var p8 = Promise.resolve("hi");
    p8.then(function(s){
        console.log(s);
    });//hi
    // 不带参数，直接得到一个Peomise对象
    var p9 = Promise.resolve();
    p9.then(function(value){
        //...
    });

    // Promise.reject() 返回一个新的Promise实例状态为rejected 回调函数立即执行
    var p10 = Promise.reject("出错了");
    //var p10 = new Promise((resolve, reject) => reject("出错了"));
    p10.then(null, function(s){
        console.log(s);
    });

    // 附加方法
    // done()抛出任何可能的错误
    //someAsyncThing().then().then().done();
    Promise.prototype.done = function(onFulfilled, onRejected){
       this.then(onFulfilled, onRejected)
           .catch(function(reason) {
            //抛出全局错误
               setTimeout(() => {throw reason},0);
           }
       )
    };
    // finally()   指定不管Promise状态如何都要执行的操作
    //使用finally方法关掉服务器
    // server.listen(0)
    //     .then(function(){
    //         // run test
    //     })
    //     .finally(server.stop);
    Promise.prototype.finally = function(callback){
      let p = this.constructor;
      return this.then(
          value => p.resolve(callback()).then(() => value),
          reason => p.resolve(callback()).then(() => {throw  reason})
      );
    };

    // 应用
    // 加载图片 一旦加载完成Promise状态发生变化
    const preloadImage = function(path){
        return new Promise(function(resolve, reject){
            var imaage = new Image();
            image.onload = resolve;
            imaage.onerror = reject;
            imaage.src = path;
        });
    };

    // Promise.try() 不区分是同步函数还是异步函数，同步同步执行，异步异步执行
    // 第一种方法
    const f = () => console.log("now");
    (async () => f())();//如果是异步立即执行async函数
    // (async () => f())().then();
    console.log("next");// now  next
    // 第二种方法 使用new Promise()
    (
        () => new Promise(
            resolve => resolve(f())
        )
    )();
    console.log("next");//now next
</script>
</html>